# Add image url 


"""Add image_url to content

Revision ID: 73588a61b6c7
Revises: 96bda03054b3
Create Date: 2026-02-11 16:38:30.718956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73588a61b6c7'
down_revision: Union[str, Sequence[str], None] = '96bda03054b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'image_url')
    # ### end Alembic commands ###
