#add video url 

"""add_video_url

Revision ID: c9d0db9beaa7
Revises: 73588a61b6c7
Create Date: 2026-02-11 18:57:44.327117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d0db9beaa7'
down_revision: Union[str, Sequence[str], None] = '73588a61b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'video_url')
    # ### end Alembic commands ###
